/*
 * fileSystemManager.h
 *
 *  Created on: 17/6/2017
 *      Author: utnso
 */

#ifndef MODULE_FILESYSTEM_FILESYSTEMMANAGER_H_
#define MODULE_FILESYSTEM_FILESYSTEMMANAGER_H_

#define OPEN_FD_SUCCESS 1
#define DELETE_FD_SUCCESS 2
#define CLOSE_FD_SUCCESS 3
#define SEEK_FD_SUCCESS 4
#define WRITE_FD_SUCCESS 5
#define READ_FD_SUCCESS 6

#define PERMISSIONS_DENIED_FD_FAILURE 10
#define FILE_NOTFOUND_FD_FAILURE 11
#define FILE_IN_USED_FD_FAILUERE 12

#endif /* MODULE_FILESYSTEM_FILESYSTEMMANAGER_H_ */
