/*
 * protocol-memory-identification.h
 *
 *  Created on: 29/4/2017
 *      Author: utnso
 */

#ifndef SRC_DC_COMMONS_PROTOCOL_MEMORY_IDENTIFICATION_H_
#define SRC_DC_COMMONS_PROTOCOL_MEMORY_IDENTIFICATION_H_

#define COD_GET_IDENTIFICATION 1000

#endif /* SRC_DC_COMMONS_PROTOCOL_MEMORY_IDENTIFICATION_H_ */
